"""persist the available categories for reuse

Revision ID: 061c063b29ee
Revises: 2ca69820bd3f
Create Date: 2019-01-27 20:17:13.583220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061c063b29ee'
down_revision = '2ca69820bd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_category_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.String(length=25), nullable=True),
    sa.Column('fill_color', sa.String(length=25), nullable=True),
    sa.Column('line_color', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('available_category_key')
    # ### end Alembic commands ###
