"""Added auth_type

Revision ID: 0c90462c5b3f
Revises: 37be289afe4e
Create Date: 2018-10-10 19:06:03.006622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c90462c5b3f'
down_revision = '37be289afe4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auth_type')
    # ### end Alembic commands ###
