"""aggregations for gradient

Revision ID: 120f2c195c85
Revises: 8736b0913e3e
Create Date: 2019-01-01 16:10:38.653609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120f2c195c85'
down_revision = '8736b0913e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_gradient_aggregate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('gradient', sa.Integer(), nullable=True),
    sa.Column('total_seconds_at_gradient', sa.Integer(), nullable=True),
    sa.Column('total_seconds_above_gradient', sa.Integer(), nullable=True),
    sa.Column('total_metres_at_gradient', sa.Integer(), nullable=True),
    sa.Column('total_metres_above_gradient', sa.Integer(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_gradient_aggregate')
    # ### end Alembic commands ###
