"""new flag for overwritten elevation data

Revision ID: 14281ceeef0c
Revises: 233e0bf1db15
Create Date: 2019-02-04 21:38:42.016788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14281ceeef0c'
down_revision = '233e0bf1db15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('is_overwritten_elevation_gain', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'is_overwritten_elevation_gain')
    # ### end Alembic commands ###
