"""Extra calendar attributes that will be needed for navigation and joining

Revision ID: 18c47cadd7a2
Revises: 3eb060c2b87b
Create Date: 2018-10-28 12:24:44.347011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c47cadd7a2'
down_revision = '3eb060c2b87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_day', sa.Column('calendar_year', sa.Integer(), nullable=True))
    op.add_column('calendar_day', sa.Column('day_of_week', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_day', 'day_of_week')
    op.drop_column('calendar_day', 'calendar_year')
    # ### end Alembic commands ###
