"""New entity for ActivityCadenceAggregate

Revision ID: 2125138fd418
Revises: e777c108836f
Create Date: 2018-10-27 12:20:38.153609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2125138fd418'
down_revision = 'e777c108836f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_cadence_aggregate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('cadence', sa.Integer(), nullable=True),
    sa.Column('total_seconds_at_cadence', sa.Integer(), nullable=True),
    sa.Column('total_seconds_above_cadence', sa.Integer(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_cadence_aggregate')
    # ### end Alembic commands ###
