"""fix inconsistent field name

Revision ID: 2fae2163c8b6
Revises: e34b60971b09
Create Date: 2019-01-19 09:25:09.159561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fae2163c8b6'
down_revision = 'e34b60971b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_activity', sa.Column('planned_distance', sa.Integer(), nullable=True))
    op.drop_column('scheduled_activity', 'target_distance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_activity', sa.Column('target_distance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('scheduled_activity', 'planned_distance')
    # ### end Alembic commands ###
