"""added field for sets

Revision ID: 3356af60589a
Revises: 061c063b29ee
Create Date: 2019-01-27 22:42:44.246214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3356af60589a'
down_revision = '061c063b29ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_exercise_type', sa.Column('default_sets', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_exercise_type', 'default_sets')
    # ### end Alembic commands ###
