"""empty message

Revision ID: 37be289afe4e
Revises: 4c94be31a48a
Create Date: 2018-10-02 21:17:24.337965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37be289afe4e'
down_revision = '4c94be31a48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_type', sa.Column('default_reps', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_type', 'default_reps')
    # ### end Alembic commands ###
