"""Adding CalendarDay table

Revision ID: 3eb060c2b87b
Revises: e36f8792eb59
Create Date: 2018-10-28 10:21:12.561415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb060c2b87b'
down_revision = 'e36f8792eb59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=True),
    sa.Column('calendar_week_start_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_day_calendar_date'), 'calendar_day', ['calendar_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_day_calendar_date'), table_name='calendar_day')
    op.drop_table('calendar_day')
    # ### end Alembic commands ###
