"""New entity for Training Goals

Revision ID: 4a5fa00cee2f
Revises: 18c47cadd7a2
Create Date: 2018-11-02 21:18:48.211546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5fa00cee2f'
down_revision = '18c47cadd7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('goal_period', sa.String(length=20), nullable=True),
    sa.Column('goal_start_date', sa.Date(), nullable=True),
    sa.Column('goal_metric', sa.String(length=50), nullable=True),
    sa.Column('goal_dimension_value', sa.String(length=50), nullable=True),
    sa.Column('goal_target', sa.Numeric(), nullable=True),
    sa.Column('current_metric_value', sa.Numeric(), nullable=True),
    sa.Column('goal_status', sa.String(length=20), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_goal')
    # ### end Alembic commands ###
