"""Extra column for metric units

Revision ID: 4d25fcbb02aa
Revises: 4a5fa00cee2f
Create Date: 2018-11-02 21:25:10.275175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d25fcbb02aa'
down_revision = '4a5fa00cee2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_goal', sa.Column('goal_metric_units', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_goal', 'goal_metric_units')
    # ### end Alembic commands ###
