"""Removed original category field on type

Revision ID: 4f4cb1fd21ca
Revises: 8a004cf93edc
Create Date: 2018-10-18 22:28:04.124042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4cb1fd21ca'
down_revision = '8a004cf93edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_type', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_type', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
