"""columns for once only exercise scheduling

Revision ID: 586d35c767d0
Revises: eb112d26bada
Create Date: 2019-02-28 18:19:38.106910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586d35c767d0'
down_revision = 'eb112d26bada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_exercise', sa.Column('recurrence', sa.String(length=20), nullable=True))
    op.add_column('scheduled_exercise', sa.Column('scheduled_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_exercise', 'scheduled_date')
    op.drop_column('scheduled_exercise', 'recurrence')
    # ### end Alembic commands ###
