"""new preference for flexible weekly planning

Revision ID: 6709cf9ab965
Revises: cf0e97444677
Create Date: 2019-04-06 10:40:42.046824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6709cf9ab965'
down_revision = 'cf0e97444677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_weekly_flexible_planning_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_weekly_flexible_planning_enabled')
    # ### end Alembic commands ###
