"""Adding Exercise Category entity

Revision ID: 78e2298b7160
Revises: 5139be8583c0
Create Date: 2018-10-17 20:32:03.281798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e2298b7160'
down_revision = '5139be8583c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_key', sa.String(length=25), nullable=True),
    sa.Column('category_name', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exercise_type', sa.Column('exercise_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercise_type', 'exercise_category', ['exercise_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_type', type_='foreignkey')
    op.drop_column('exercise_type', 'exercise_category_id')
    op.drop_table('exercise_category')
    # ### end Alembic commands ###
