"""added uom preference to model

Revision ID: 84f16013e52b
Revises: ac5fb49f2969
Create Date: 2019-03-23 12:37:22.730776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f16013e52b'
down_revision = 'ac5fb49f2969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('distance_uom_preference', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'distance_uom_preference')
    # ### end Alembic commands ###
