"""columns for scheduled exercises and activities using flexible weekly planning

Revision ID: 8617da7e086f
Revises: 6709cf9ab965
Create Date: 2019-04-06 14:31:37.632406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8617da7e086f'
down_revision = '6709cf9ab965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_activity', sa.Column('planning_period', sa.String(length=20), nullable=True))
    op.add_column('scheduled_exercise', sa.Column('planning_period', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_exercise', 'planning_period')
    op.drop_column('scheduled_activity', 'planning_period')
    # ### end Alembic commands ###
