"""flags for whether features are used

Revision ID: 8736b0913e3e
Revises: a399c1651a58
Create Date: 2018-12-29 14:46:18.818675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8736b0913e3e'
down_revision = 'a399c1651a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_categories_user', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_exercises_user', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_strava_user', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_training_goals_user', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_training_plan_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_training_plan_user')
    op.drop_column('user', 'is_training_goals_user')
    op.drop_column('user', 'is_strava_user')
    op.drop_column('user', 'is_exercises_user')
    op.drop_column('user', 'is_categories_user')
    # ### end Alembic commands ###
