"""Added class for pace aggregation

Revision ID: 8e4f2325e35d
Revises: b973e8795572
Create Date: 2019-01-23 20:55:46.822118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4f2325e35d'
down_revision = 'b973e8795572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_pace_aggregate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('pace_seconds', sa.Integer(), nullable=True),
    sa.Column('total_seconds_at_pace', sa.Integer(), nullable=True),
    sa.Column('total_seconds_above_pace', sa.Integer(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_pace_aggregate')
    # ### end Alembic commands ###
