"""support scheudling of activities for one date only

Revision ID: 99b2ad98244d
Revises: 14281ceeef0c
Create Date: 2019-02-28 16:14:37.254393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b2ad98244d'
down_revision = '14281ceeef0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_activity', sa.Column('scheduled_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_activity', 'scheduled_date')
    # ### end Alembic commands ###
