"""Adding removed flag to scheduled exercises

Revision ID: 9d9067839da1
Revises: 4f4cb1fd21ca
Create Date: 2018-10-20 21:34:55.570752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9067839da1'
down_revision = '4f4cb1fd21ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_exercise', sa.Column('is_removed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_exercise', 'is_removed')
    # ### end Alembic commands ###
