"""Model changes to support today training plan

Revision ID: a399c1651a58
Revises: 06a85ae1d5ee
Create Date: 2018-12-28 15:52:15.331175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a399c1651a58'
down_revision = '06a85ae1d5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_for_today',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_exercise_id', sa.Integer(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_exercise_id'], ['scheduled_exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('last_login_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_datetime')
    op.drop_table('exercise_for_today')
    # ### end Alembic commands ###
