"""extra column for subtype on scheduled activity

Revision ID: a4deab1aba3f
Revises: 8617da7e086f
Create Date: 2019-04-27 15:26:02.866666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4deab1aba3f'
down_revision = '8617da7e086f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_activity', sa.Column('activity_subtype', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_activity', 'activity_subtype')
    # ### end Alembic commands ###
