"""new objects for skipping dates with weekly activities and exercises

Revision ID: ac5fb49f2969
Revises: 586d35c767d0
Create Date: 2019-02-28 22:30:53.782451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5fb49f2969'
down_revision = '586d35c767d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_activity_skipped_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_activity_id', sa.Integer(), nullable=True),
    sa.Column('skipped_date', sa.Date(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_activity_id'], ['scheduled_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_exercise_skipped_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_exercise_id', sa.Integer(), nullable=True),
    sa.Column('skipped_date', sa.Date(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_exercise_id'], ['scheduled_exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_exercise_skipped_date')
    op.drop_table('scheduled_activity_skipped_date')
    # ### end Alembic commands ###
