"""flag for marketing opt-in

Revision ID: d2ec7594002f
Revises: 3356af60589a
Create Date: 2019-01-29 22:01:07.503009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ec7594002f'
down_revision = '3356af60589a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_opted_in_for_marketing_emails', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_opted_in_for_marketing_emails')
    # ### end Alembic commands ###
