"""Support for measurement in seconds

Revision ID: dc7250f14b2b
Revises: 0c90462c5b3f
Create Date: 2018-10-10 22:32:00.792475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7250f14b2b'
down_revision = '0c90462c5b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('seconds', sa.Integer(), nullable=True))
    op.add_column('exercise_type', sa.Column('default_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_type', 'default_seconds')
    op.drop_column('exercise', 'seconds')
    # ### end Alembic commands ###
