"""added elevation uom preference

Revision ID: e1d1d315debc
Revises: 84f16013e52b
Create Date: 2019-03-23 17:05:53.627147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d1d315debc'
down_revision = '84f16013e52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('elevation_uom_preference', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'elevation_uom_preference')
    # ### end Alembic commands ###
