"""new model for scheduled activity

Revision ID: e34b60971b09
Revises: 09e821a4ff89
Create Date: 2019-01-19 09:13:36.804627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34b60971b09'
down_revision = '09e821a4ff89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('scheduled_day', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('target_distance', sa.Integer(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('is_removed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_for_today',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_activity_id', sa.Integer(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_activity_id'], ['scheduled_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activity', sa.Column('scheduled_activity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activity', 'scheduled_activity', ['scheduled_activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_column('activity', 'scheduled_activity_id')
    op.drop_table('activity_for_today')
    op.drop_table('scheduled_activity')
    # ### end Alembic commands ###
