"""Adding median cadence

Revision ID: e36f8792eb59
Revises: 2125138fd418
Create Date: 2018-10-27 12:33:36.995380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36f8792eb59'
down_revision = '2125138fd418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('median_cadence', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'median_cadence')
    # ### end Alembic commands ###
