"""Adding entity and relationships for Activity

Revision ID: e777c108836f
Revises: 9d9067839da1
Create Date: 2018-10-24 21:50:53.481801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e777c108836f'
down_revision = '9d9067839da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_source', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('is_race', sa.Boolean(), nullable=True),
    sa.Column('distance', sa.Numeric(), nullable=True),
    sa.Column('elapsed_time', sa.Interval(), nullable=True),
    sa.Column('moving_time', sa.Interval(), nullable=True),
    sa.Column('average_speed', sa.Numeric(), nullable=True),
    sa.Column('average_cadence', sa.Numeric(), nullable=True),
    sa.Column('average_heartrate', sa.Numeric(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
