"""column to explicitly state recurrence on scheduled activity

Revision ID: eb112d26bada
Revises: 99b2ad98244d
Create Date: 2019-02-28 16:22:09.739465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb112d26bada'
down_revision = '99b2ad98244d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_activity', sa.Column('recurrence', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_activity', 'recurrence')
    # ### end Alembic commands ###
