"""Added relationship from exercise to scheduled exercise

Revision ID: f4667ab21f4a
Revises: 0c88a1b4071b
Create Date: 2018-10-13 17:08:15.125265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4667ab21f4a'
down_revision = '0c88a1b4071b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('scheduled_exercise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercise', 'scheduled_exercise', ['scheduled_exercise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_column('exercise', 'scheduled_exercise_id')
    # ### end Alembic commands ###
